# Site settings
title: WebDev Blog
email: sxbarrows@gmail.com
description: WebDev blog.
baseurl: "/dev-blog"

twitter_username: isusieq
avatar: "https://pbs.twimg.com/profile_images/1374784582/susan3_400x400.JPG" # Set footer avatar
paginate: 3

# Build settings
markdown: kramdown
permalink: /:title

# Default Settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Susan Barrowsr" # Set default author name
      categories: "development"
      layout: "post"
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
